### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [FeloVilches/Hanzi#28]
avoid coding like this:
```js
db.query("UPDATE comment SET text='$1^' WHERE comment_id=$2 RETURNING *;", [text, id])
```
It is quite dangerous. Not only it doesn't format the text correctly, but also opens it to SQL injection.

You should just use the standard variable in such cases:
````js
db.query("UPDATE comment SET text=$1 WHERE comment_id=$2 RETURNING *", [text, id])
```
you have it in multiple places ;)

**Comment by FeloVilches** [comment]
I know, thanks! It's in one of the issues to fix the queries and prepare them correctly actually haha

**Comment by vitaly-t** [comment]
You are welcome!

In preparing queries nicely keep in mind [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html), it is very nice for keeping all your SQL externally ;)

See also [Query Files](https://github.com/vitaly-t/pg-promise#query-files).
